version: '3'
services:
  mysql:
    image: mysql
    ports: 
      - "3306:3306"
    volumes:
      - "./mysql:/var/lib/mysql"
    environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: sandbox
  redis:
    image: "redis:2.8"
    ports:
      - "6379:6379"
    volumes:
      - "./redis:/data"
  app:
    build: ./app
    volumes:
      - "./app:/usr/local/nginx/html"
  nginx:
    image: "nginx:latest"
    ports:
      - "80:80"
    volumes:
      - "./nginx:/usr/share/nginx/html"
  rails:
    build: "./rails"
    ports:
      - "3000:3000"
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    links:
      - mysql
    volumes:
      - "./rails:/myapp"
    environment:
      - "RAILS_ENV=development"